//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSIRT.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OSIRT.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File successfully attached to case..
        /// </summary>
        internal static string AttacFile_successfully_attached_to_case_ {
            get {
                return ResourceManager.GetString("AttacFile_successfully_attached_to_case_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment.
        /// </summary>
        internal static string AttachmentAction {
            get {
                return ResourceManager.GetString("AttachmentAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to view the image in the system&apos;s default image viewing application..
        /// </summary>
        internal static string CannotOpenImagePanel_SetLinkLabelText_Click_here_to_view_the_image_in_the_system_s_default_image_viewing_application_ {
            get {
                return ResourceManager.GetString("CannotOpenImagePanel_SetLinkLabelText_Click_here_to_view_the_image_in_the_system_" +
                        "s_default_image_viewing_application_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the location for the case container.
        /// </summary>
        internal static string case_location_desc {
            get {
                return ResourceManager.GetString("case_location_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A case container already exists with this name. Please chose another..
        /// </summary>
        internal static string case_with_that_name_exists_already {
            get {
                return ResourceManager.GetString("case_with_that_name_exists_already", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning up... Please Wait.
        /// </summary>
        internal static string CaseClosingCleanUpPanel_Cleaning_up____Please_Wait {
            get {
                return ResourceManager.GetString("CaseClosingCleanUpPanel_Cleaning_up____Please_Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Details.
        /// </summary>
        internal static string CaseDetailsHeader {
            get {
                return ResourceManager.GetString("CaseDetailsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Location.
        /// </summary>
        internal static string CaseLocation {
            get {
                return ResourceManager.GetString("CaseLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Notes.
        /// </summary>
        internal static string CaseNotes {
            get {
                return ResourceManager.GetString("CaseNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Reference.
        /// </summary>
        internal static string CaseReference {
            get {
                return ResourceManager.GetString("CaseReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Help.
        /// </summary>
        internal static string CloseCasePanel_uiPasswordHelpLabel_Click_Password_Help {
            get {
                return ResourceManager.GetString("CloseCasePanel_uiPasswordHelpLabel_Click_Password_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combing screenshots... Please wait.
        /// </summary>
        internal static string CombineScreenshots {
            get {
                return ResourceManager.GetString("CombineScreenshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating New Case... Please Wait.
        /// </summary>
        internal static string creating_case_wait {
            get {
                return ResourceManager.GetString("creating_case_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string DownloadedAction {
            get {
                return ResourceManager.GetString("DownloadedAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evidence Reference.
        /// </summary>
        internal static string EvidenceReference {
            get {
                return ResourceManager.GetString("EvidenceReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loads an existing OSIRT case to continue working on.
        /// </summary>
        internal static string ExisitingCase {
            get {
                return ResourceManager.GetString("ExisitingCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field can only contain letters, numbers, hyphens (&apos;-&apos;) and underscores (&apos;_&apos;).
        /// </summary>
        internal static string field_can_only_contain_valid_directory_char {
            get {
                return ResourceManager.GetString("field_can_only_contain_valid_directory_char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        internal static string field_is_required {
            get {
                return ResourceManager.GetString("field_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File with this name already exists in the attachment folder..
        /// </summary>
        internal static string File_with_this_name_already_exists_in_the_attachment_folder {
            get {
                return ResourceManager.GetString("File_with_this_name_already_exists_in_the_attachment_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash Funtion.
        /// </summary>
        internal static string HashFunction {
            get {
                return ResourceManager.GetString("HashFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to safely close the current case?.
        /// </summary>
        internal static string In_order_to_safely_close_a_case__you_are_required_to_enter_the_case_password__Would_you_like_to_enter_the_case_password_now_ {
            get {
                return ResourceManager.GetString("In_order_to_safely_close_a_case__you_are_required_to_enter_the_case_password__Wou" +
                        "ld_you_like_to_enter_the_case_password_now_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investigating Agency.
        /// </summary>
        internal static string InvestigatingAgency {
            get {
                return ResourceManager.GetString("InvestigatingAgency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investigating Officer.
        /// </summary>
        internal static string InvestigatingOfficer {
            get {
                return ResourceManager.GetString("InvestigatingOfficer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded.
        /// </summary>
        internal static string LoadedAction {
            get {
                return ResourceManager.GetString("LoadedAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load an OSIRT case to view its audit log..
        /// </summary>
        internal static string LoadReport {
            get {
                return ResourceManager.GetString("LoadReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a brand new OSIRT case.
        /// </summary>
        internal static string NewCase {
            get {
                return ResourceManager.GetString("NewCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Name.
        /// </summary>
        internal static string OperationName {
            get {
                return ResourceManager.GetString("OperationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a note..
        /// </summary>
        internal static string Please_enter_a_note {
            get {
                return ResourceManager.GetString("Please_enter_a_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot.
        /// </summary>
        internal static string ScreenshotAction {
            get {
                return ResourceManager.GetString("ScreenshotAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snippet.
        /// </summary>
        internal static string SnippetAction {
            get {
                return ResourceManager.GetString("SnippetAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        internal static string VideoAction {
            get {
                return ResourceManager.GetString("VideoAction", resourceCulture);
            }
        }
    }
}
